from mycompiler.pyqtui.base import UiControllerBase


# noinspection PyMethodMayBeStatic
class UiController(UiControllerBase):
    ''' Controller for a PyQt5 uic-created ui, autogenerated
    from script pyqtui.uicompiler.py.
    
    Class body is generated from the list of connections
    found in the .ui file generated by QtDesigner, and should
    in all cases always have a list of every connection made
    with appropriate arguments, a simple docstring, and
    simple annotation.
    
    This class, located at:
    
    C:\Users\Administrator\Documents\Programming\PythonSource\source\mycompiler\pyqtui\uicontroller.py
    
    should therefore only be used with its co-generated class at:
    
    C:\Users\Administrator\Documents\Programming\PythonSource\source\mycompiler\pyqtui\ideui.py
    
    Failure to do so may result in mismatched signal/slot
    definitions in the view setupUi() protocol.
    
    '''

    def changeCFlagMenuList(self, QString):
        '''Signal handler from widget 'cflagsCategoryMenu' connecting
        signal'QString'.
        '''
        print("changeCFlagMenuList called", QString)
        return None
    def cFlagListDoubleClick(self, QModelIndex):
        '''Signal handler from widget 'cflagsList' connecting
        signal'QModelIndex'.
        '''
        print("cFlagListDoubleClick called", QModelIndex)
        return None
    def cFlagAddClicked(self, QBool):
        '''Signal handler from widget 'cflagsAddBtn' connecting
        signal'QBool'.
        '''
        print("cFlagAddClicked called", QBool)
        return None
    def cFlagRemovedClicked(self, QBool):
        '''Signal handler from widget 'cflagsRemoveBtn' connecting
        signal'QBool'.
        '''
        print("cFlagRemovedClicked called", QBool)
        return None
    def cFlagCurrentDoubleClicked(self, QModelIndex):
        '''Signal handler from widget 'cflagsCurrentList' connecting
        signal'QModelIndex'.
        '''
        print("cFlagCurrentDoubleClicked called", QModelIndex)
        return None
    def outfileBrowseBtnClicked(self, QBool):
        '''Signal handler from widget 'browseOutfileBtn' connecting
        signal'QBool'.
        '''
        print("outfileBrowseBtnClicked called", QBool)
        return None
    def outfileEditReturnPressed(self, ):
        '''Signal handler from widget 'browseOutfileEdit' connecting
        signal''.
        '''
        print("outfileEditReturnPressed called", )
        return None
    def compileClicked(self, QBool):
        '''Signal handler from widget 'compileBtn' connecting
        signal'QBool'.
        '''
        print("compileClicked called", QBool)
        return None
    def executeClicked(self, QBool):
        '''Signal handler from widget 'executeBtn' connecting
        signal'QBool'.
        '''
        print("executeClicked called", QBool)
        return None
    def runLastClicked(self, QBool):
        '''Signal handler from widget 'runLastBtn' connecting
        signal'QBool'.
        '''
        print("runLastClicked called", QBool)
        return None
    def compilerChoiceMenuChanged(self, QString):
        '''Signal handler from widget 'ccChoiceMenu' connecting
        signal'QString'.
        '''
        print("compilerChoiceMenuChanged called", QString)
        return None
    def sourceBrowseBtnClicked(self, QBool):
        '''Signal handler from widget 'browseSourceBtn' connecting
        signal'QBool'.
        '''
        print("sourceBrowseBtnClicked called", QBool)
        return None
    def generateMakefileClicked(self, QBool):
        '''Signal handler from widget 'generateMakefileBtn' connecting
        signal'QBool'.
        '''
        print("generateMakefileClicked called", QBool)
        return None
    def makefileSaveClicked(self, QBool):
        '''Signal handler from widget 'makefileSaveBtn' connecting
        signal'QBool'.
        '''
        print("makefileSaveClicked called", QBool)
        return None
    def makefileSaveAsClicked(self, QBool):
        '''Signal handler from widget 'makefileSaveAsBtn' connecting
        signal'QBool'.
        '''
        print("makefileSaveAsClicked called", QBool)
        return None
    def makefileOpenClicked(self, QBool):
        '''Signal handler from widget 'makefileOpenBtn' connecting
        signal'QBool'.
        '''
        print("makefileOpenClicked called", QBool)
        return None
    def runMakefileClicked(self, QBool):
        '''Signal handler from widget 'makefileRunBtn' connecting
        signal'QBool'.
        '''
        print("runMakefileClicked called", QBool)
        return None
    def makefileDoUseClicked(self, QBool):
        '''Signal handler from widget 'makefileCkBox' connecting
        signal'QBool'.
        '''
        print("makefileDoUseClicked called", QBool)
        return None
    def makefileDoActionChanged(self, QString):
        '''Signal handler from widget 'makefileRunMenu' connecting
        signal'QString'.
        '''
        print("makefileDoActionChanged called", QString)
        return None