from mycompiler.pyqtui.base import UiControllerBase
from PyQt5.QtWidgets import QMainWindow


# noinspection PyMethodMayBeStatic
class UiController(UiControllerBase):
    ''' Controller for a PyQt5 uic-created ui, autogenerated
    from script C:/Users/Administrator/Documents/Programming/PythonSource/source/mycompiler/pyqtui/uicompiler.py.
    
    Class body is generated from the list of connections
    found in the .ui file generated by QtDesigner, and should
    in all cases always have a list of every connection made
    with appropriate arguments, a simple docstring, and
    simple annotation.
    
    This class, located at:
    
    C:/Users/Administrator/Documents/Programming/PythonSource/source/mycompiler/pyqtui/uicontroller_auto.py
    
    should therefore only be used with its co-generated class at:
    
    C:/Users/Administrator/Documents/Programming/PythonSource/source/mycompiler/pyqtui/ideui.py
    
    Failure to do so may result in mismatched signal/slot
    definitions in the view setupUi() protocol.
    
    '''
