from PyQt5 import QtCore, QtGui, QtWidgets

class mainWindowView():
    def setupUi(self, mainWindow, controller):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(930, 683)
        mainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ConsoleIOText = QtWidgets.QTextEdit(self.centralwidget)
        self.ConsoleIOText.setGeometry(QtCore.QRect(483, 422, 411, 162))
        self.ConsoleIOText.setAutoFillBackground(False)
        self.ConsoleIOText.setObjectName("ConsoleIOText")
        self.ConsoleIOLabel = QtWidgets.QLabel(self.centralwidget)
        self.ConsoleIOLabel.setGeometry(QtCore.QRect(483, 402, 61, 16))
        self.ConsoleIOLabel.setObjectName("ConsoleIOLabel")
        self.cmdPreviewText = QtWidgets.QLineEdit(self.centralwidget)
        self.cmdPreviewText.setGeometry(QtCore.QRect(483, 382, 411, 20))
        self.cmdPreviewText.setObjectName("cmdPreviewText")
        self.cmdPreviewLabel = QtWidgets.QLabel(self.centralwidget)
        self.cmdPreviewLabel.setGeometry(QtCore.QRect(483, 362, 71, 16))
        self.cmdPreviewLabel.setObjectName("cmdPreviewLabel")
        self.cflagsList = QtWidgets.QListView(self.centralwidget)
        self.cflagsList.setGeometry(QtCore.QRect(34, 95, 171, 192))
        self.cflagsList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cflagsList.setObjectName("cflagsList")
        self.ccChoiceMenu = QtWidgets.QComboBox(self.centralwidget)
        self.ccChoiceMenu.setGeometry(QtCore.QRect(30, 30, 111, 21))
        self.ccChoiceMenu.setObjectName("ccChoiceMenu")
        self.ccChoiceMenu.addItem("")
        self.compileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.compileBtn.setGeometry(QtCore.QRect(621, 592, 75, 23))
        self.compileBtn.setObjectName("compileBtn")
        self.executeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.executeBtn.setGeometry(QtCore.QRect(698, 592, 75, 23))
        self.executeBtn.setObjectName("executeBtn")
        self.ccLabel = QtWidgets.QLabel(self.centralwidget)
        self.ccLabel.setGeometry(QtCore.QRect(30, 10, 61, 16))
        self.ccLabel.setObjectName("ccLabel")
        self.cflagsLabel = QtWidgets.QLabel(self.centralwidget)
        self.cflagsLabel.setGeometry(QtCore.QRect(34, 75, 46, 13))
        self.cflagsLabel.setObjectName("cflagsLabel")
        self.cflagsCategoryMenu = QtWidgets.QComboBox(self.centralwidget)
        self.cflagsCategoryMenu.setGeometry(QtCore.QRect(80, 70, 121, 22))
        self.cflagsCategoryMenu.setObjectName("cflagsCategoryMenu")
        self.cflagsCategoryMenu.addItem("")
        self.cflagsCategoryMenu.addItem("")
        self.cflagsCategoryMenu.addItem("")
        self.cflagsCategoryMenu.addItem("")
        self.cflagsCategoryMenu.addItem("")
        self.cflagsCurrentList = QtWidgets.QListView(self.centralwidget)
        self.cflagsCurrentList.setGeometry(QtCore.QRect(234, 95, 171, 192))
        self.cflagsCurrentList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cflagsCurrentList.setObjectName("cflagsCurrentList")
        self.cflagsAddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cflagsAddBtn.setGeometry(QtCore.QRect(84, 295, 75, 23))
        self.cflagsAddBtn.setObjectName("cflagsAddBtn")
        self.cflagsRemoveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cflagsRemoveBtn.setGeometry(QtCore.QRect(284, 295, 75, 23))
        self.cflagsRemoveBtn.setObjectName("cflagsRemoveBtn")
        self.cflagsCurrentLabel = QtWidgets.QLabel(self.centralwidget)
        self.cflagsCurrentLabel.setGeometry(QtCore.QRect(234, 75, 81, 16))
        self.cflagsCurrentLabel.setObjectName("cflagsCurrentLabel")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(480, 96, 417, 190))
        self.listView.setObjectName("listView")
        self.sourceLabel = QtWidgets.QLabel(self.centralwidget)
        self.sourceLabel.setGeometry(QtCore.QRect(480, 70, 46, 13))
        self.sourceLabel.setObjectName("sourceLabel")
        self.outfileLabel = QtWidgets.QLabel(self.centralwidget)
        self.outfileLabel.setGeometry(QtCore.QRect(479, 315, 46, 13))
        self.outfileLabel.setObjectName("outfileLabel")
        self.browseOutfileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.browseOutfileEdit.setGeometry(QtCore.QRect(479, 335, 340, 20))
        self.browseOutfileEdit.setObjectName("browseOutfileEdit")
        self.runLastBtn = QtWidgets.QPushButton(self.centralwidget)
        self.runLastBtn.setGeometry(QtCore.QRect(775, 592, 75, 23))
        self.runLastBtn.setObjectName("runLastBtn")
        self.browseOutfileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.browseOutfileBtn.setGeometry(QtCore.QRect(822, 333, 75, 23))
        self.browseOutfileBtn.setObjectName("browseOutfileBtn")
        self.sourceBrowseEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sourceBrowseEdit.setGeometry(QtCore.QRect(479, 289, 341, 20))
        self.sourceBrowseEdit.setObjectName("sourceBrowseEdit")
        self.browseSourceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.browseSourceBtn.setGeometry(QtCore.QRect(822, 288, 75, 23))
        self.browseSourceBtn.setObjectName("browseSourceBtn")
        self.makefileOpenBtn = QtWidgets.QPushButton(self.centralwidget)
        self.makefileOpenBtn.setGeometry(QtCore.QRect(297, 591, 75, 23))
        self.makefileOpenBtn.setObjectName("makefileOpenBtn")
        self.sourceLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.sourceLabel_2.setGeometry(QtCore.QRect(31, 363, 46, 13))
        self.sourceLabel_2.setObjectName("sourceLabel_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 382, 378, 201))
        self.textEdit.setObjectName("textEdit")
        self.generateMakefileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.generateMakefileBtn.setGeometry(QtCore.QRect(66, 591, 75, 23))
        self.generateMakefileBtn.setObjectName("generateMakefileBtn")
        self.makefileCkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.makefileCkBox.setGeometry(QtCore.QRect(182, 360, 90, 17))
        self.makefileCkBox.setObjectName("makefileCkBox")
        self.makefileRunBtn = QtWidgets.QPushButton(self.centralwidget)
        self.makefileRunBtn.setGeometry(QtCore.QRect(542, 592, 75, 23))
        self.makefileRunBtn.setObjectName("makefileRunBtn")
        self.makefileSaveAsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.makefileSaveAsBtn.setGeometry(QtCore.QRect(220, 591, 75, 23))
        self.makefileSaveAsBtn.setObjectName("makefileSaveAsBtn")
        self.makefileSaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.makefileSaveBtn.setGeometry(QtCore.QRect(143, 591, 75, 23))
        self.makefileSaveBtn.setObjectName("makefileSaveBtn")
        self.makefileRunMenu = QtWidgets.QComboBox(self.centralwidget)
        self.makefileRunMenu.setGeometry(QtCore.QRect(87, 358, 86, 22))
        self.makefileRunMenu.setObjectName("makefileRunMenu")
        self.makefileRunMenu.addItem("")
        self.makefileRunMenu.addItem("")
        self.makefileRunMenu.addItem("")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 930, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionNew_2 = QtWidgets.QAction(mainWindow)
        self.actionNew_2.setCheckable(True)
        self.actionNew_2.setObjectName("actionNew_2")
        self.actionOpen = QtWidgets.QAction(mainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(mainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionLanguage = QtWidgets.QAction(mainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.actionCompile_and_Run = QtWidgets.QAction(mainWindow)
        self.actionCompile_and_Run.setObjectName("actionCompile_and_Run")
        self.actionRun_Last = QtWidgets.QAction(mainWindow)
        self.actionRun_Last.setObjectName("actionRun_Last")
        self.menuFile.addAction(self.actionNew_2)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuConfig.addAction(self.actionLanguage)
        self.menuRun.addAction(self.actionCompile_and_Run)
        self.menuRun.addAction(self.actionRun_Last)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())

        self.retranslateUi(mainWindow)
        self.cflagsCategoryMenu.currentIndexChanged['QString'].connect(controller.changeCFlagMenuList)
        self.cflagsList.doubleClicked['QModelIndex'].connect(controller.cFlagListDoubleClick)
        self.cflagsAddBtn.clicked.connect(controller.cFlagAddClicked)
        self.cflagsRemoveBtn.clicked.connect(controller.cFlagRemovedClicked)
        self.cflagsCurrentList.doubleClicked['QModelIndex'].connect(controller.cFlagCurrentDoubleClicked)
        self.browseOutfileBtn.clicked.connect(controller.outfileBrowseBtnClicked)
        self.browseOutfileEdit.returnPressed.connect(controller.outfileEditReturnPressed)
        self.compileBtn.clicked.connect(controller.compileClicked)
        self.executeBtn.clicked.connect(controller.executeClicked)
        self.runLastBtn.clicked.connect(controller.runLastClicked)
        self.ccChoiceMenu.currentIndexChanged['QString'].connect(controller.compilerChoiceMenuChanged)
        self.browseSourceBtn.clicked.connect(controller.sourceBrowseBtnClicked)
        self.generateMakefileBtn.clicked.connect(controller.generateMakefileClicked)
        self.makefileSaveBtn.clicked.connect(controller.makefileSaveClicked)
        self.makefileSaveAsBtn.clicked.connect(controller.makefileSaveAsClicked)
        self.makefileOpenBtn.clicked.connect(controller.makefileOpenClicked)
        self.makefileRunBtn.clicked.connect(controller.runMakefileClicked)
        self.makefileCkBox.clicked.connect(controller.makefileDoUseClicked)
        self.makefileRunMenu.currentTextChanged['QString'].connect(controller.makefileDoActionChanged)
